2019-03-06 13:32:57 [tasks ERROR] Sending mail error: [Errno -2] Name or service not known
2019-03-06 15:47:12 [log ERROR] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view jumpserver.views.IndexView didn't return an HttpResponse object. It returned None instead.
2019-03-06 15:51:08 [log ERROR] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view jumpserver.views.IndexView didn't return an HttpResponse object. It returned None instead.
2019-03-06 15:51:42 [log ERROR] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view jumpserver.views.IndexView didn't return an HttpResponse object. It returned None instead.
